global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s